question_data =[
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The Great Wall of China is visible from the moon.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "'Ananas' is mostly used as the word for Pineapple in other languages.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The color orange is named after the fruit.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The Lego Group was founded in 1932.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The National Animal of Scotland is the Unicorn.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Slovakia is a member of European Union-",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The mitochondria is the powerhouse of the cell.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ]